x-email-env: &email-env
  EMAIL_URL: ${EMAIL_URL:-smtp://smtp:1025}

services:
  backend:
    volumes:
      - static-data:/project/static
    ports:
      - 8000:8000
    depends_on:
      migrate:
        condition: service_completed_successfully
      collectstatic:
        condition: service_completed_successfully
      create_admin:
        condition: service_completed_successfully
    develop:
      watch:
        - action: restart
          path: .env
        - action: sync+restart
          path: project
          target: /project/project
        - action: sync+restart
          path: api
          target: /project/api
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: Dockerfile

  migrate:
    profiles: !reset []

  collectstatic:
    profiles: !reset []

  create_admin:
    depends_on:
      migrate:
        condition: service_completed_successfully
    profiles: !reset []

  celery:
    environment:
      <<: *email-env
    depends_on:
      migrate:
        condition: service_completed_successfully
      smtp:
        condition: service_healthy
    develop:
      watch:
        - action: restart
          path: .env
        - action: sync+restart
          path: project
          target: /project/project
        - action: sync+restart
          path: api
          target: /project/api
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: Dockerfile

  db:
    ports:
      - 55432:5432

  smtp:
    image: axllent/mailpit:v1.29
    environment:
      MP_DATABASE: /data/mailpit.db
    volumes:
      - mailpit-data:/data
    networks:
      - backend
    ports:
      - 8025:8025 # Web UI
      - 1025:1025 # SMTP server
    healthcheck:
      test: /mailpit readyz
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  proxy:
    depends_on:
      collectstatic:
        condition: service_completed_successfully
    develop:
      watch:
        - action: restart
          path: ./nginx.conf

volumes:
  mailpit-data:
