# Generated by Django 6.0.3 on 2026-04-11 18:52

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')), # type: ignore
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('house', models.CharField(max_length=50, verbose_name='house')),
                ('structure', models.CharField(blank=True, max_length=8, verbose_name='structure')),
                ('building', models.CharField(blank=True, max_length=8, verbose_name='building')),
                ('apartment', models.CharField(max_length=8, verbose_name='apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
