# Generated by Django 6.0.3 on 2026-04-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_parameter_product_shop_shopoffer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.CharField(max_length=120, verbose_name='parameter value'),
        ),
    ]
