# Generated by Django 6.0.3 on 2026-04-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_orderitem_order_uq_order_single_basket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'product parameter', 'verbose_name_plural': 'product parameters'},
        ),
    ]
