# Generated by Django 6.0.3 on 2026-04-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productparameter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.order',),
        ),
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.order',),
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ck_order_contact_not_null',
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('basket', 'Basket'), ('new', 'New'), ('confirmed', 'Confirmed'), ('assembled', 'Assembled'), ('sent', 'Sent'), ('completed', 'Completed')], verbose_name='state'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', {'basket', 'cancelled'}), ('contact__isnull', False), _connector='OR'), name='ck_order_contact_not_null'),
        ),
    ]
