# Generated by Django 6.0.3 on 2026-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_basket_placedorder_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='uq_order_single_basket',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'basket')), fields=('user', 'state'), name='uq_order_single_basket'),
        ),
    ]
