# Generated by Django 6.0.3 on 2026-05-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_order_uq_order_single_basket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('pk',), 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('pk',), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('pk',), 'verbose_name': 'order item', 'verbose_name_plural': 'order items'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('pk',), 'verbose_name': 'parameter', 'verbose_name_plural': 'parameters'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('pk',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'ordering': ('pk',), 'verbose_name': 'product parameter', 'verbose_name_plural': 'product parameters'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('pk',), 'verbose_name': 'shop', 'verbose_name_plural': 'shops'},
        ),
        migrations.AlterModelOptions(
            name='shopoffer',
            options={'ordering': ('pk',), 'verbose_name': 'shop offer', 'verbose_name_plural': 'shop offers'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('-created',), 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('pk',)},
        ),
    ]
