# Generated by Django 6.0.5 on 2026-05-16 19:38

import api.models
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=api.models.user_avatar_upload_to, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnails_ready',
            field=models.BooleanField(db_index=True, default=False, verbose_name='avatar thumbnails ready'),
        ),
    ]
