"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('DJANGO_SECRET_KEY', 'django-example-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', False)

SQL_TRACE = env.bool('SQL_TRACE', False)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', str, [])  # type: ignore[reportArgumentType]


# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Auxilary apps
    'admin_extra_buttons',
    'django_filters',
    'phonenumber_field',
    'rest_framework',
    # Project apps
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if SQL_TRACE:
    MIDDLEWARE = [
        # Install helper middleware which logs SQL query stats
        'project.middleware.DebugSQLQueryStatsMiddleware',
        *MIDDLEWARE,
    ]


if DEBUG:
    # Install Django Debug Toolbar
    INSTALLED_APPS += ['debug_toolbar']

    MIDDLEWARE = [
        # The Debug Toolbar middleware must be as early as possible in the list
        'debug_toolbar.middleware.DebugToolbarMiddleware',
        *MIDDLEWARE,
    ]

    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': 'project.middleware.show_debug_toolbar',
    }


ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Celery configuration
# https://docs.celeryq.dev/en/stable/userguide/configuration.html

CELERY_BROKER_URL = env.url(
    'CELERY_BROKER_URL',
    default='redis://default:redis_password@localhost:6379/0',  # pyright: ignore[reportArgumentType]
)
CELERY_WORKER_CONCURRENCY = env.int('CELERY_WORKER_CONCURRENCY', 1)


APP_LOG_LEVEL = 'DEBUG' if DEBUG else 'INFO'
DJANGO_DB_LOG_LEVEL = 'DEBUG' if SQL_TRACE else 'WARNING'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'rich': {
            'format': '%(message)s',
            'datefmt': '[%X]',
        },
        'pretty_sql': {
            '()': 'project.logging.PrettySQLFormatter',
            'format': '%(message)s',
            'datefmt': '[%X]',
        },
    },
    'handlers': {
        'console': {
            'class': 'rich.logging.RichHandler',
            'level': 'INFO',
            'formatter': 'rich',
            'rich_tracebacks': True,
            'tracebacks_show_locals': False,
            'show_time': True,
            'show_level': True,
            'show_path': True,
            'markup': True,
        },
        'console_debug': {
            'class': 'rich.logging.RichHandler',
            'level': 'DEBUG',
            'formatter': 'rich',
            'rich_tracebacks': True,
            'tracebacks_show_locals': False,
            'show_time': True,
            'show_level': True,
            'show_path': True,
            'markup': True,
        },
        'console_debug_sql': {
            'class': 'rich.logging.RichHandler',
            'level': 'DEBUG',
            'formatter': 'pretty_sql',
            'rich_tracebacks': True,
            'tracebacks_show_locals': False,
            'show_time': True,
            'show_level': True,
            'show_path': True,
            'markup': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # Project logging
        'api': {
            'handlers': ['console_debug'],
            'level': APP_LOG_LEVEL,
            'propagate': False,
        },
        'project': {
            'handlers': ['console_debug'],
            'level': APP_LOG_LEVEL,
            'propagate': False,
        },
        # Django basic logging
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django request handling errors
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django runserver logs
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django SQL queries debug logs
        'django.db.backends': {
            'handlers': ['console_debug_sql'],
            'level': DJANGO_DB_LOG_LEVEL,
            'propagate': False,
        },
        # Some libraries
        'asyncio': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'httpx': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'httpcore': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# Email configuration
# https://docs.djangoproject.com/en/6.0/ref/settings/#email-backend

EMAIL_CONFIG = env.email(
    'EMAIL_URL',
    default='consolemail://',  # pyright: ignore[reportArgumentType]
)
locals().update(EMAIL_CONFIG)

DEFAULT_FROM_EMAIL = env.str(
    'DEFAULT_FROM_EMAIL',
    default='webmaster@localhost',
)


REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'api.utils.exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': (
        'rest_framework.pagination.LimitOffsetPagination'
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default='sqlite:///db.sqlite3',  # type: ignore[reportArgumentType]
    ),
}

AUTH_USER_MODEL = 'api.User'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = env.path(
    'STATIC_ROOT',
    default=BASE_DIR / STATIC_URL,  # pyright: ignore[reportArgumentType]
)
