"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('DJANGO_SECRET_KEY', 'django-example-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', False)

SQL_TRACE = env.bool('SQL_TRACE', False)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', str, [])  # type: ignore[reportArgumentType]


# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Auxilary apps
    'admin_extra_buttons',
    'cachalot',
    'django_filters',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'easy_thumbnails',
    'phonenumber_field',
    'rest_framework',
    'social_django',
    # Project apps
    'api',
]

MIDDLEWARE = [
    'project.middleware.SocialAuthAPIExceptionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if SQL_TRACE:
    MIDDLEWARE = [
        # Install helper middleware which logs SQL query stats
        'project.middleware.DebugSQLQueryStatsMiddleware',
        *MIDDLEWARE,
    ]


if DEBUG:
    # Install Django Debug Toolbar
    INSTALLED_APPS += ['debug_toolbar']

    MIDDLEWARE = [
        # The Debug Toolbar middleware must be as early as possible in the list
        'debug_toolbar.middleware.DebugToolbarMiddleware',
        *MIDDLEWARE,
    ]

    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': 'project.middleware.show_debug_toolbar',
    }

    PANELS_DEFAULTS = [
        # Default panels
        'debug_toolbar.panels.history.HistoryPanel',
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.alerts.AlertsPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.community.CommunityPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
        # django-cachalot
        'cachalot.panels.CachalotPanel',
    ]


# Silk configuration
# https://github.com/jazzband/django-silk

SILK_ENABLED = env.bool('SILK_ENABLED', default=False)

if SILK_ENABLED:
    INSTALLED_APPS += ['silk']

    MIDDLEWARE = [
        'silk.middleware.SilkyMiddleware',
        *MIDDLEWARE,
    ]


ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

# Celery configuration
# https://docs.celeryq.dev/en/stable/userguide/configuration.html

CELERY_BROKER_URL = env.url(
    'CELERY_BROKER_URL',
    default='redis://default:redis_password@localhost:6379/0',  # pyright: ignore[reportArgumentType]
)
CELERY_WORKER_CONCURRENCY = env.int('CELERY_WORKER_CONCURRENCY', 1)


APP_LOG_LEVEL = 'DEBUG' if DEBUG else 'INFO'
DJANGO_DB_LOG_LEVEL = 'DEBUG' if SQL_TRACE else 'WARNING'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'rich': {
            'format': '%(message)s',
            'datefmt': '[%X]',
        },
        'pretty_sql': {
            '()': 'project.logging.PrettySQLFormatter',
            'format': '%(message)s',
            'datefmt': '[%X]',
        },
    },
    'handlers': {
        'console': {
            'class': 'rich.logging.RichHandler',
            'level': 'INFO',
            'formatter': 'rich',
            'rich_tracebacks': True,
            'tracebacks_show_locals': False,
            'show_time': True,
            'show_level': True,
            'show_path': True,
            'markup': True,
        },
        'console_debug': {
            'class': 'rich.logging.RichHandler',
            'level': 'DEBUG',
            'formatter': 'rich',
            'rich_tracebacks': True,
            'tracebacks_show_locals': False,
            'show_time': True,
            'show_level': True,
            'show_path': True,
            'markup': True,
        },
        'console_debug_sql': {
            'class': 'rich.logging.RichHandler',
            'level': 'DEBUG',
            'formatter': 'pretty_sql',
            'rich_tracebacks': True,
            'tracebacks_show_locals': False,
            'show_time': True,
            'show_level': True,
            'show_path': True,
            'markup': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # Project logging
        'api': {
            'handlers': ['console_debug'],
            'level': APP_LOG_LEVEL,
            'propagate': False,
        },
        'project': {
            'handlers': ['console_debug'],
            'level': APP_LOG_LEVEL,
            'propagate': False,
        },
        # Django basic logging
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django request handling errors
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django runserver logs
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django SQL queries debug logs
        'django.db.backends': {
            'handlers': ['console_debug_sql'],
            'level': DJANGO_DB_LOG_LEVEL,
            'propagate': False,
        },
        # Some libraries
        'asyncio': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'httpx': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'httpcore': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# Email configuration
# https://docs.djangoproject.com/en/6.0/ref/settings/#email-backend

EMAIL_CONFIG = env.email(
    'EMAIL_URL',
    default='consolemail://',  # pyright: ignore[reportArgumentType]
)
locals().update(EMAIL_CONFIG)

DEFAULT_FROM_EMAIL = env.str(
    'DEFAULT_FROM_EMAIL',
    default='webmaster@localhost',
)


REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'api.utils.exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (),
    'DEFAULT_PAGINATION_CLASS': (
        'rest_framework.pagination.LimitOffsetPagination'
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'api.throttling.AnonRateThrottle',
        'api.throttling.UserRateThrottle',
        'api.throttling.ScopedRateThrottle',
        'api.throttling.EmailScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/min',
        'user': '10/sec',
        'registration': '20/min',
        'email': '1/3min',
        'verify': '5/min',
        'login': '5/min',
        'order': '1/5sec',
    },
    'NUM_PROXIES': 1,
    'DEFAULT_SCHEMA_CLASS': 'api.schema.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Backend service for purchase automation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'COMPONENT_SPLIT_REQUEST': True,
}

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        **env.db(
            'DATABASE_URL',
            default='sqlite:///db.sqlite3',  # type: ignore[reportArgumentType]
        ),
        'CONN_MAX_AGE': 0,
    }
}

# Cache
# https://docs.djangoproject.com/en/6.0/ref/settings/#caches

CACHES = {
    'default': {
        **env.cache(
            'CACHE_URL',
            default='filecache://.cache',  # pyright: ignore[reportArgumentType]
        ),
    }
}

AUTH_USER_MODEL = 'api.User'

# Authentication backends
# https://docs.djangoproject.com/en/6.0/ref/settings/#authentication-backends

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',  # Django default auth backend
)

# Python Social Auth settings
# Authentication backends:
# https://python-social-auth.readthedocs.io/en/latest/configuration/django.html
# https://python-social-auth.readthedocs.io/en/latest/backends/index.html#supported-backends

SOCIAL_AUTH_ADMIN_USER_SEARCH_FIELDS = ('email', 'first_name', 'last_name')
SOCIAL_AUTH_JSONFIELD_ENABLED = True
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/api/v1/user/login/social/success'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/api/v1/user/login/social/error'
SOCIAL_AUTH_SANITIZE_REDIRECTS = True

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'api.pipeline.require_verified_email',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'api.pipeline.save_social_avatar',
)

# Google Oauth2 settings
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env.str(
    'GOOGLE_OAUTH2_CLIENT_ID',
    default='example.apps.googleusercontent.com',
)
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env.str(
    'GOOGLE_OAUTH2_CLIENT_SECRET',
    default='EXAMPLE-CLIENT-SECRET',
)
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'prompt': 'select_account',
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = env.path(
    'STATIC_ROOT',
    default=BASE_DIR / STATIC_URL,  # pyright: ignore[reportArgumentType]
)

# User-uploaded files
# https://docs.djangoproject.com/en/6.0/topics/files/

MEDIA_URL = 'media/'
MEDIA_ROOT = env.path(
    'MEDIA_ROOT',
    default=BASE_DIR / MEDIA_URL,  # pyright: ignore[reportArgumentType]
)

# easy-thumbnails settings
# https://easy-thumbnails.readthedocs.io/en/latest/ref/settings/

THUMBNAIL_ALIASES = {
    'api.User.avatar': {
        'avatar_small': {
            'size': (64, 64),
            'crop': True,
            'quality': 85,
        },
        'avatar_medium': {
            'size': (256, 256),
            'crop': True,
            'quality': 90,
        },
        'avatar_large': {
            'size': (512, 512),
            'crop': True,
            'quality': 90,
        },
    },
}

MAX_AVATAR_SIZE = 5 * 1024 * 1024  # 5 MiB


# Sentry console settings
# https://docs.sentry.io/platforms/python/integrations/django/


SENTRY_ENABLED = env.bool('SENTRY_ENABLED', default=False)

if SENTRY_ENABLED:
    import sentry_sdk

    SENTRY_URL = env.str(
        'SENTRY_URL',
        default='https://key@example.sentry.io/123456',  # pyright: ignore[reportArgumentType]
    )

    sentry_sdk.init(
        dsn=SENTRY_URL,
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
        # Enable sending logs to Sentry
        enable_logs=True,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        traces_sample_rate=1.0,
    )
